# Generated by Django 5.1.6 on 2025-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentintent_options_paymentintent_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
