# Generated by Django 5.1.6 on 2025-03-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hosted_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
