# Generated by Django 5.1.6 on 2025-03-26 13:13

import cart.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=cart.models.get_default_product, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
