"""
Django settings for BasicCommerce project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*qhuh!l3+5%ka2^wrm$0k7s1k+ti60cj+r*3&%p*w6ajdne*(d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    # 'rest_framework.authtoken',
    'djoser',
    'accounts',
    'phonenumber_field',
    'phonenumbers',
    'catalog',
    'django_filters',
    'corsheaders',
    'cart',
    #'orders',
    'payment',
    'shipping',
    'wishlist',
    'promotions',
    'orders.apps.OrdersConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BasicCommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BasicCommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'basiccommerceDB',
        'USER': 'postgres',
        'PASSWORD': 'dev.shivlab',
        'HOST': 'localhost',  # Or the IP address of your PostgreSQL server
        'PORT': '5432',       # Default PostgreSQL port
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',

    ),
    'DEFAULT_PAGINATION_CLASS': 'catalog.pagination.ProductPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_THROTTLE_CLASSES': ['catalog.throttling.ProductListThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        'product_list': '100/day',  # Throttle product list API to 100 requests per day
        'cart': '100/day',  # You can add custom throttle rates for cart endpoints
        'order': '100/day', 
        'payment': '100/day',  # Throttle payment API to 100 requests per day


    },

}




DJOSER = {
     'USER_CREATE_PASSWORD_RETYPE': True, # confirm password to prevent typos
     "USER_ID_FIELD": "username", # unique identifier for user accounts
    'SERIALIZERS': {
        'user_create': 'accounts.serializers.CustomUserCreateSerializer',
        'user': 'accounts.serializers.UserSerializer',
        'user': 'accounts.serializers.UserProfileSerializer',

    },
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('JWT',),
}
AUTH_USER_MODEL = 'accounts.User'
PHONENUMBER_DEFAULT_REGION = "IN" #Specify a Default Region

#FrontEnd
CORS_ALLOW_HEADERS = [
    'sessionid',
    'content-type',
    'x-csrftoken',
    'accept',
    'accept-encoding',
    'authorization',
    'x-requested-with',
]

CORS_ORIGIN_WHITELIST = [
    'http://localhost:5173',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]

STRIPE_SECRET_KEY = 'sk_test_51R16gP2YuXLFtG78w98eXi5zLEzQvUJQcdHcKOcjCNbEEzBW0AmqcThzCiyLlGO7rMsGstD1u1Uam6IdFQVcJao100uFtn2FVs'
STRIPE_PUBLIC_KEY = 'pk_test_51R16gP2YuXLFtG78NXPLLieQYu1eKUrSaiz7qSC6Gf25ExrAZqr6GjbBHYj8sRjXqbMRVqyUjh5OBVIkmlc4Ktiu00jyozVLud'
STRIPE_WEBHOOK_SECRET = 'whsec_5a194b23e2f2e7938059d49dad8853e37b486b15ab1552719fdb3d8412e20185'
# STRIPE_WEBHOOK_SECRET = 'whsec_7f70465b1e0041eb793229e88d0dbc0b278d5de93c48e6fddde970eaceaf1f0b'
#mail 

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = False
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'sender22210@gmail.com'
EMAIL_HOST_PASSWORD = 'ygef nqsv itgv rwnw'
DEFAULT_FROM_EMAIL = 'sender22210@gmail.com'

DOMAIN = "http://127.0.0.1:8000/payment/"
